# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CLI Package

on:
  release:
    types: [created]
    paths:
      - 'packages/cli/**'

jobs:
  install-cli:
    name: "CLI: NPM Install"
    defaults:
      run:
        working-directory: packages/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install

  publish-cli:
    name: "CLI: NPM Publish"
    needs: install-cli
    defaults:
      run:
        working-directory: packages/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: |
          if git diff --name-only HEAD^ HEAD | grep -qvE '^packages/cli/'; then
            echo "No changes in packages/cli directory. Skipping NPM publish."
          else
            npm publish --access=public
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}